# Generated by Django 5.0 on 2023-12-17 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('position_at_work', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=80)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='humen', related_query_name='human', to='OneToOne.employee')),
            ],
        ),
    ]
