# Generated by Django 5.0 on 2023-12-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneToOne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='phone',
            field=models.CharField(max_length=40),
        ),
    ]
