# Generated by Django 5.0 on 2023-12-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('electronics', 'электроника'), ('gadgets', 'гаджеты'), ('computers', 'комьпютеры'), ('clothes', 'одежда'), ('shoes', 'обувь'), ('household', 'домашнии товары')], max_length=70)),
                ('products', models.ManyToManyField(related_name='categories', related_query_name='category', to='ManyToMany.product')),
            ],
        ),
    ]
