# Generated by Django 5.0 on 2023-12-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManyToMany', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('electronics', 'Электроника'), ('gadgets', 'Гаджеты'), ('computers', 'Компьютеры'), ('clothes', 'Одежда'), ('shoes', 'Обувь'), ('household', 'Домашние товары')], max_length=70),
        ),
    ]
